# application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
  
spec:
  project: default

  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: nginx    
    targetRevision: "15.4.2"
    helm:
      values: |-
        nameOverride: "nginx"
          
  destination:
    namespace: nginx
    server: "https://kubernetes.default.svc"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true