apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  #labels:
  #  argocd.argoproj.io/refresh: hard
  #finalizers:
  #  - resources-finalizer.argocd.argoproj.io  
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  
  sources:
    - repoURL: https://github.com/jei0486/demo-argocd.git  # path is missing so no manifests are generated
      targetRevision: HEAD
      ref: myRepo                                          # repo is available via symlink "myRepo"
    - repoURL: https://github.com/bitnami/charts.git
      targetRevision: HEAD
      path: bitnami/nginx                                 # path "bitnami/nginx" is used to generate manifests
      helm:
        valueFiles:
          - $myRepo/values/nginx-values.yaml              # "values/nginx-values.yaml" is located in source with reference name $myRepo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true